/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./../components/l-table-pro/crud-dialog/add.vue')['default']
    Auth: typeof import('./../components/auth/auth.vue')['default']
    AuthAll: typeof import('./../components/auth/authAll.vue')['default']
    Auths: typeof import('./../components/auth/auths.vue')['default']
    Edit: typeof import('./../components/l-table-pro/crud-dialog/edit.vue')['default']
    ImageUpload: typeof import('./../components/image-upload/index.vue')['default']
    Loading: typeof import('./../components/loading/index.vue')['default']
    LSvgIcon: typeof import('./../components/l-svg-icon/index.vue')['default']
    LTablePro: typeof import('./../components/l-table-pro/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/svgIcon/index.vue')['default']
  }
}
